MAX_LENGTH_EMAIL_ADDRESS = 254
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_LENGTH_USERNAME = 150

MAX_LENGTH_NAME = 256
MAX_LENGTH_SLUG = 50
MAX_LENGTH_TEXT = 5000

MAX_LENGTH_UNIT = 20
MAX_AMOUNT_INGREDIENTS = 32
MIN_AMOUNT_INGREDIENTS = 1
MAX_COOKING_TIME = 300
MIN_COOKING_TIME = 1

FONT_SIZE_HEADER = 16
FONT_SIZE_INGREDIENTS = 10
INDENT_TOP_REGULAR = 40
INDENT_LEFT_REGULAR = 30
INDENT_AFTER_HEADER = 30
INDENT_BETWEEN_INGREDIENTS = 20

PDF_FILENAME = "spisok_pokupok.pdf"
SHORT_LINK_URL_PATH = "s"

SHORT = 'short'
MEDIUM = 'medium'
LONG = 'long'

MAX_TIME = 40
MIN_TIME = 20
