# Generated by Django 3.2 on 2024-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240728_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug_for_short_url',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Слаг для короткой ссылки'),
        ),
    ]
